project:
  type: website

website:
  title: "Piyush's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
comments: 
  hypothesis:
    theme: clean
    openSidebar: false
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
execute:
  freeze: auto
resources:
  - CNAME


