project:
  type: website

website:
  title: "Piyush's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jainds
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/jainpiyush.bsky.social
  site-url: "https://piyush.dev"
comments: 
  hypothesis:
    theme: clean
    openSidebar: false
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
execute:
  freeze: auto
resources:
  - CNAME


